### ISSUE TITLE
many requests for application registration - no response at all

### ISSUE THREAD

**Issue by hophoff** [huamitech/rest-api#18]
Several times in 2019 and in 2020 I did a request for application registration, and I got never a response (also not in the spam/junk folder). @huamitech @jimzhangji @ShiliangHM @dingyong-hm is there any possibility to get in contact? I get every week requests from users to add an integration to my app with Mi Fit. It would be so nice to be able to add this integration.

**Comment by dingyong-hm** [comment]
Has the application registration information been sent to the relevant mailbox?

**Comment by dingyong-hm** [comment]
> Several times in 2019 and in 2020 I did a request for application registration, and I got never a response (also not in the spam/junk folder). @huamitech @jimzhangji @ShiliangHM @dingyong-hm is there any possibility to get in contact? I get every week requests from users to add an integration to my app with Mi Fit. It would be so nice to be able to add this integration.

Has the application registration information been sent to the relevant mailbox?

**Comment by hophoff** [comment]
Hi, thanks for your response. I sent several times an introduction email as described on the wiki page to partner@huami.com Last year and this year, never a response. Should I try again or is there another email address?  

> _Please send registration email to partner@huami.com, with a short introduction to your organization and your application._

**Comment by dingyong-hm** [comment]
> Hi, thanks for your response. I sent several times an introduction email as described on the wiki page to [partner@huami.com](mailto:partner@huami.com) Last year and this year, never a response. Should I try again or is there another email address?
> 
> > _Please send registration email to [partner@huami.com](mailto:partner@huami.com), with a short introduction to your organization and your application._

Please go to the official open platform to apply for data cooperation, the official website address is https://dev.huami.com/#/home, Thanks.

**Comment by hophoff** [comment]
@dingyong-hm Thanks for your support!
