### ISSUE TITLE
Application registration

### ISSUE THREAD

**Issue by mb-software** [huamitech/rest-api#2]
Hello,

I would like to use the huami web API in a small web application. I have already sent an email to partner@huami.com with my request one week ago. But I did not get any response. Please help, I need to register a client id and get a client secret to make my first tests with the API.

Thanks for your support

http://navicomputer.com

**Comment by FHantke** [comment]
Hello @NaviComputer , did you get an answer yet? I emailed partner@huami.com some days ago, but they didn't respond.

**Comment by mb-software** [comment]
No response at all...bad behaviour by Huami...

**Comment by YangShuqing** [comment]
@jimzhangji @ShiliangHM may help

**Comment by jimzhanghm** [comment]
@NaviComputer @FHantke ，Huami has dedicated BD folks, who evaluate all the requests, and prioritize them according to strategic impact. Anyways, sorry you didn't get any response, but likely your request has been deprioritized.

**Comment by design-media** [comment]
I've contacted Huami over 1month ago... and still no answer. @jimzhanghm @ShiliangHM could you help with this? The review process is really really slow.
