### ISSUE TITLE
Authorization Issues

### ISSUE THREAD

**Issue by melih9779** [huamitech/rest-api#22]
Hello,
I am having login problem, can you help me?

Login response code:
{"code":-50000,"message":"Failed to process the request. Detailed error message has been logged on server side."}

app info:
{"appId":"********","appType":"WEB","displayName":"****","packageId":"","codeSignature":"","bundleId":"","deviceType":4,"scopes":[],"sportTypes":"[\"OUTDOOR_RUN\",\"DISTANCE_RUN\",\"TIME_RUN\",\"CALORIE_RUN\",\"INTERVAL_RUN\",\"WALKING\",\"TRAILRUN\",\"TREADMILL\",\"OUTDOOR_CYCLING\",\"INDOOR_CYCLING\",\"SKIING\",\"ELLIPTICL\",\"MOUNTAINEER\",\"INDOOR_SWIM\",\"OPEN_WATER_SWIM\",\"TRIATHLON\"]","status":1,"ttl"...........

**Comment by dingyong-hm** [comment]
please provider the complete curl,3ks
