### ISSUE TITLE
OAuth 2.0 (Web Site)

### ISSUE THREAD

**Issue by klaushh** [huamitech/rest-api#23]
I like to get an access_token and refresh_token for my user like the documentation (https://github.com/huamitech/rest-api/wiki#obtaining-user-consent-and-tokens-web-site) but I always get the error "=-1002&message=Missing%20required%20parameter%20scope".
The sample didn't show any scope param and if I try to add some, the error is same.

This is my url I redirect my user to:
https://user.huami.com/oauth/index.html#/?client_id=XXX&redirect_uri=XXX&response_type=code&scope=activity_daily

First the login window is shown.
![login_window](https://user-images.githubusercontent.com/19150370/115960258-a0287d80-a510-11eb-977e-fd03168d7310.png)

After the login with my account I get this error.
![error_allow](https://user-images.githubusercontent.com/19150370/115960359-3b215780-a511-11eb-9227-cab3054d7ab0.png)

After "allow" I come back to my website with error in url "=-1002&message=Missing%20required%20parameter%20scope".

How can I add the scope to the authenticat process?

**Comment by mvo42** [comment]
Hello @klaushh, 
I'm encountering the same issue on my end.
Have you found the answer?

**Comment by mvo42** [comment]
^ Update on this

The link provided on the github documentation is wrong.

We should follow this documentation instead:
https://dev.huami.com/#/home/docs/

To get access_token and refresh_token, this link works:
https://user.huami.com/oauth2/index.html#/login?client_id={client_id}&redirect_uri={redirect_uri}&response_type={response_type}&state={state}

It's from: https://dev.huami.com/#/home/docs/data/purchase?page=webSDK

**Comment by klaushh** [comment]
> https://user.huami.com/oauth2/index.html#/login?client_id={client_id}&redirect_uri={redirect_uri}&response_type={response_type}&state={state}

You are the best! Thank you very much!
